USE equipmentcheckoutsystem;

INSERT INTO equipment (NAME, QUANTITY, DESCRIPTION)
VALUES ('Hammer', 10, 'Stanley 5oz.'),
		('Wrench', 10, 'GearWrench Combination Set'),
        ('Socket Wrench', 10, 'DEWALT 192-Piece Mechanics Tool Set'),
        ('Philips-Head Screwdriver', 10, 'Tekton DRV49002'),
        ('Flat-Head Screwdriver', 10, 'Phillips Flat Head Screwdriver'),
        ('Moon Wrench', 10, 'Sunex 9935M'),
        ('Adjustable Wrench', 10, 'Channellock Adjustable Wrench'),
        ('Handsaw', 10, 'Home Planet Gear Folding Hand Saw'),
        ('Mallet', 10, 'TEKTON Fiberglass Handle Rubber Mallet'),
        ('Pocketknife', 10, 'Buck Knives'),
        ('Scissors', 10, 'Joewell Shears'),
        ('Electric Drill', 10, 'DeWalt DCD701F2 Xtreme 12V'),
        ('Pliers', 10, 'Vampliers Pro Linesman Pliers'),
        ('Needle Nose Pliers', 10, 'Stanley 84-096 Needle Nose Plier'),
        ('Plunger', 10, 'Korky 99-4A Max Performance Plunger'),
        ('Stepladder', 10, 'Delxo Lightweight Aluminum Woodgrain 3 Step Ladder'),
        ('Caulking Gun', 10, 'Newborn 250 Smooth Rod Revolving Frame Caulking Gun'),
        ('Vice Grip', 10, 'Wilton WS8 Shop Vise'),
        ('2d Nail', 10, 'HILLMAN'),
        ('10d Nail', 10, 'HILLMAN'),
        ('50d Nail', 10, 'HILLMAN'),
        ('5/16 Bolt', 10, 'ARP'),
        ('3/8 Bolt', 10, 'ARP'),
        ('7/16 Bolt', 10, 'ARP'),
        ('#6 Screw', 10, 'FastenMaster'),
        ('#8 Screw', 10, 'FastenMaster'),
        ('#10 Screw', 10, 'FastenMaster');